### ISSUE TITLE
tracking SDK progress (`indigo/atproto/*`)

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/indigo#378]
Sketching out what a more stable "golang atproto SDK" might look like.

- [x] `atproto/syntax`: syntax types for Handle, DID, NSID, AT-URI, TID
- [x] `atproto/crypto`: basically go-did pulled in to this monorepo, and DID-specific stuff removed. smaller API surface specifically for atproto, abstracting away most implementation details and config knobs
- [x] `atproto/identity`: combined handle and DID resolution. interface for caching/persistent services
- [ ] `atproto/data`: runtime helpers for data model, possibly using `go-ipld-prime`. eg, for working with records and JSON when you don't know the schema. DAG-CBOR to JSON conversion.
- [ ] `atproto/lexicon`: generic Lexicon helpers, and types for dealing with Lexicon schema JSON itself. likely runtime schema verification. the sort of utils which get referenced by codegen'd code
- [ ] `atproto/repo`: MST and repository implementation, including CAR import/export, diff processing, verification, interfaces
- [ ] `atproto/client`: generic HTTP client ("XRPC"), with ergonomic auth help. possibly generic stream (WebSocket) client helpers also. no codegen stuff for specific Lexicons.

Codegen tooling and codegen output (record types, client APIs, server handlers) would probably live elsewhere, at least for a while.
